export type ParkingType = 'showroom' | 'outdoor' | 'home'
/** 'manual' = added by the admin and paid outside Stripe (cash/transfer/WhatsApp). */
export type PaymentStatus = 'pending' | 'paid' | 'failed' | 'refunded' | 'manual'
/** Lifecycle of a booking — simplified 4-stage pipeline (shared with the admin app):
 *      New → Confirmed → In Progress → Completed   (+ Cancelled / Refunded)
 *  plus the internal `pending_payment` hold. DB values are historical (the admin's
 *  migration 006/007); the labels below are what's shown.
 *  - `pending_payment`        — hold created, waiting for Stripe payment (30 min).
 *  - `paid_new`               — "New": paid; awaiting the team's WhatsApp time confirmation.
 *  - `time_confirmed`         — "Confirmed": arrival time confirmed with the customer.
 *  - `inspection_in_progress` — "In Progress": inspecting / writing the report.
 *  - `report_sent`            — "Completed": report delivered to the customer.
 *  - `cancelled`              — covers both Cancelled and Refunded (payment_status says which). */
export type BookingStatus =
  | 'pending_payment'
  | 'paid_new'
  | 'time_confirmed'
  | 'inspection_in_progress'
  | 'report_sent'
  | 'cancelled'

/** Human labels for each booking status (shared contract with the admin app). */
export const BOOKING_STATUS_LABELS: Record<BookingStatus, string> = {
  pending_payment: 'Pending Payment',
  paid_new: 'New',
  time_confirmed: 'Confirmed',
  inspection_in_progress: 'In Progress',
  report_sent: 'Completed',
  cancelled: 'Cancelled / Refunded',
}

export type PackageId = 'standard' | 'comprehensive' | 'premium'
export type Emirate = 'Abu Dhabi' | 'Dubai' | 'Sharjah' | 'Ajman' | 'Umm Al Quwain' | 'Ras Al Khaimah' | 'Fujairah' | 'Al Ain'
/** Fixed daily inspection slots (DB values, Asia/Dubai). Display via slotLabel(). */
export type SlotTime = '09:30' | '11:45' | '14:00' | '16:15' | '18:30'
/** Stored at booking time so rule changes never reinterpret old rows.
 *  'long' = Abu Dhabi / Ras Al Khaimah / Fujairah / Al Ain (AED 100 travel fee,
 *  bookable at 09:30 only, also blocks the 11:45 travel buffer). */
export type DistanceClass = 'normal' | 'long'

/** One row in a package card's feature list — ticked (included) or crossed (not). */
export interface PackageFeature {
  label: string
  included: boolean
}

export interface Package {
  id: PackageId
  name: string
  price: number // AED
  /** Premium is flagged recommended (red badge on the card). */
  recommended?: boolean
  tagline: string
  /** Every included feature, flat — used by the checkout order summary. */
  features: string[]
  /** Core checks shown on every card (always included / green tick). */
  coreFeatures: string[]
  /** Premium-only checks: green tick on Premium, red cross on Standard. */
  extraFeatures: PackageFeature[]
  ctaLabel: string
}

/**
 * Shape collected by the checkout form and POSTed to /api/bookings.
 * Package price/name are intentionally NOT included here — the server derives
 * them from `packageId` against the canonical catalogue so a client can't spoof
 * the price.
 */
export interface BookingFormData {
  customerName: string
  customerPhone: string
  customerEmail: string
  emirate: Emirate | ''
  address: string
  locationLat: number | null
  locationLng: number | null
  parkingType: ParkingType | ''
  carMake: string
  carModel: string
  carYear: string
  additionalNotes: string
  inspectionDate: string // ISO yyyy-mm-dd (Asia/Dubai)
  slotTime: SlotTime | ''
  packageId: PackageId
}

export type BookingFormErrors = Partial<Record<keyof BookingFormData, string>>

/**
 * Camel-case booking shape used by emails / Stripe / the calendar boundary.
 * Built from a DB row via rowToRecord() — the booking id (e.g. CCB-7F3K2Q) is
 * generated by the database and IS the customer-facing reference.
 */
export interface BookingRecord {
  id: string
  status: BookingStatus
  paymentStatus: PaymentStatus
  packageId: PackageId
  packageName: string
  /** Base package price in AED, before any travel fee. */
  packagePrice: number
  /** Flat travel surcharge in AED for long-distance emirates (0 for none). */
  travelFee: number
  /** List price (packagePrice + travelFee), before any promotion code. */
  totalPrice: number
  /** What Stripe ACTUALLY charged after a promotion code, in FILS (1 AED = 100 fils),
   *  NOT AED like the prices above. NULL for pre-feature / manual bookings → fall back
   *  to totalPrice. Stored fils-exact so a percentage code never rounds. */
  amountPaid: number | null
  /** Promotion-code saving in FILS (NULL or 0 = no code used). */
  discountAmount: number | null
  /** Promotion code entered at Checkout, e.g. 'CRESCENT50' (NULL = none). */
  promoCode: string | null
  customerName: string
  customerPhone: string
  customerEmail: string | null
  carMake: string
  carModel: string
  carYear: string
  vin: string | null
  plateNumber: string | null
  emirate: Emirate
  distanceClass: DistanceClass
  parkingType: ParkingType | null
  address: string
  locationLat: number | null
  locationLng: number | null
  inspectionDate: string
  slotTime: SlotTime
  additionalNotes: string | null
  stripeSessionId: string | null
  stripePaymentIntentId: string | null
  holdExpiresAt: string | null
  paidAt: string | null
  cancelledAt: string | null
  assignedInspector: string | null
  reportId: string | null
  adminNotes: string | null
  manualBooking: boolean
  createdBy: string | null
  googleCalendarEventId: string | null
  createdAt: string
  updatedAt: string
}

/** Supabase row (snake_case). Mirrors the `bookings` table in migration
 *  006_bookings.sql (Crescent Car Reports repo — the shared database). */
export interface Booking {
  id: string
  created_at: string
  updated_at: string
  customer_name: string
  customer_phone: string
  customer_email: string | null
  emirate: string
  distance_class: DistanceClass
  address: string
  location_lat: number | null
  location_lng: number | null
  parking_type: ParkingType | null
  additional_notes: string | null
  car_make: string
  car_model: string
  car_year: string
  vin: string | null
  plate_number: string | null
  inspection_date: string
  slot_time: SlotTime
  package_id: PackageId
  package_name: string
  package_price: number
  travel_fee: number
  total_price: number
  /** Real charge after a promotion code, in FILS (NULL = unknown → use total_price). */
  amount_paid: number | null
  /** Promotion-code saving in FILS (NULL or 0 = none). */
  discount_amount: number | null
  /** Promotion code string entered at Checkout, e.g. 'CRESCENT50' (NULL = none). */
  promo_code: string | null
  stripe_session_id: string | null
  stripe_payment_intent_id: string | null
  payment_status: PaymentStatus
  booking_status: BookingStatus
  hold_expires_at: string | null
  paid_at: string | null
  cancelled_at: string | null
  assigned_inspector: string | null
  report_id: string | null
  admin_notes: string | null
  manual_booking: boolean
  created_by: string | null
  google_calendar_event_id: string | null
}
