import { createServerClient, isSupabaseConfigured } from '@/lib/supabase/server'
import { slotLabel } from '@/lib/packages'
import type {
  Booking,
  BookingRecord,
  DistanceClass,
  Emirate,
  SlotTime,
} from '@/types/booking'

/**
 * Availability + booking-hold helpers (server-only).
 *
 * The slot rules live in the shared Supabase project (Crescent Car Reports,
 * migration 006_bookings.sql): 5 fixed slots/day, long-distance emirates bookable
 * at 09:30 only (also blocking the 11:45 travel buffer), 1-hour minimum notice,
 * and a 30-minute payment hold. This module is a thin wrapper over the
 * SECURITY DEFINER RPCs — booking_slot_availability, create_booking_hold,
 * confirm_booking_paid, cancel_pending_booking — so the website can never
 * drift from the database's source of truth. Stale holds are expired inside
 * the RPCs themselves (expire_stale_holds), so there is no client-side sweep.
 *
 * Never import this from a client component: it uses the service-role Supabase
 * client. All reads/writes go through createServerClient(), which bypasses RLS.
 */

/** Public payment hold, minutes. 30 = Stripe Checkout's minimum session expiry,
 *  so the Stripe session can never outlive the database hold. */
export const HOLD_MINUTES = 30

export const ALL_SLOTS: readonly SlotTime[] = ['09:30', '11:45', '14:00', '16:15', '18:30']

export interface SlotAvailability {
  slot: SlotTime
  label: string
  available: boolean
  /** booked | blocked | travel_buffer | long_distance_first_slot_only
   *  | travel_buffer_unavailable | cutoff — null when available. */
  reason: string | null
}

/** Thrown when the slot can't be booked (taken/blocked/cutoff — the RPC raises
 *  SLOT_UNAVAILABLE, including for concurrent-insert unique violations). */
export class SlotUnavailableError extends Error {
  constructor() {
    super('That slot was just booked. Please choose another time.')
    this.name = 'SlotUnavailableError'
  }
}

function db() {
  return createServerClient()
}

function isSlotUnavailableRpcError(error: { code?: string; message?: string }): boolean {
  return Boolean(error.message?.includes('SLOT_UNAVAILABLE'))
}

/**
 * Availability for all 5 slots on `date` for a customer in `distance` class.
 * Calls the booking_slot_availability RPC (which also sweeps stale holds).
 * When Supabase isn't configured (keyless preview) every slot reports available
 * so the checkout UI still renders.
 */
export async function getSlotAvailability(
  date: string,
  distance: DistanceClass,
): Promise<SlotAvailability[]> {
  if (!isSupabaseConfigured()) {
    return ALL_SLOTS.map((slot) => ({
      slot,
      label: slotLabel(slot),
      available: distance === 'long' ? slot === '09:30' : true,
      reason: distance === 'long' && slot !== '09:30' ? 'long_distance_first_slot_only' : null,
    }))
  }

  const { data, error } = await db().rpc('booking_slot_availability', {
    p_date: date,
    p_distance: distance,
  })
  if (error) throw error

  const rows = (data ?? []) as { slot_time: SlotTime; available: boolean; reason: string | null }[]
  // Preserve canonical slot order regardless of what the DB returns.
  return ALL_SLOTS.map((slot) => {
    const row = rows.find((r) => r.slot_time === slot)
    return {
      slot,
      label: slotLabel(slot),
      available: row?.available ?? false,
      reason: row ? (row.reason ?? null) : 'unknown',
    }
  })
}

/** Input for createBookingHold — everything the create_booking_hold RPC needs.
 *  Prices are server-derived by the caller; the booking id/reference is
 *  generated by the database and returned on the row. */
export interface BookingHoldInput {
  customerName: string
  customerPhone: string
  customerEmail: string | null
  emirate: Emirate
  address: string
  locationLat: number | null
  locationLng: number | null
  parkingType: string | null
  additionalNotes: string | null
  carMake: string
  carModel: string
  carYear: string
  vin: string | null
  plateNumber: string | null
  inspectionDate: string
  slotTime: SlotTime
  packageId: string
  packageName: string
  packagePrice: number
  travelFee: number
  totalPrice: number
}

/**
 * Creates a 30-minute payment hold via the create_booking_hold RPC, which
 * validates every slot rule atomically (advisory-locked per date) and returns
 * the inserted row — including the DB-generated CCB-XXXXXX reference. Throws
 * SlotUnavailableError when the RPC raises SLOT_UNAVAILABLE.
 */
export async function createBookingHold(input: BookingHoldInput): Promise<Booking> {
  const { data, error } = await db().rpc('create_booking_hold', {
    p_customer_name: input.customerName,
    p_customer_phone: input.customerPhone,
    p_customer_email: input.customerEmail ?? '',
    p_emirate: input.emirate,
    p_address: input.address,
    p_location_lat: input.locationLat,
    p_location_lng: input.locationLng,
    p_parking_type: input.parkingType ?? '',
    p_additional_notes: input.additionalNotes ?? '',
    p_car_make: input.carMake,
    p_car_model: input.carModel,
    p_car_year: input.carYear,
    p_vin: input.vin ?? '',
    p_plate_number: input.plateNumber ?? '',
    p_inspection_date: input.inspectionDate,
    p_slot_time: input.slotTime,
    p_package_id: input.packageId,
    p_package_name: input.packageName,
    p_package_price: input.packagePrice,
    p_travel_fee: input.travelFee,
    p_total_price: input.totalPrice,
  })
  if (error) {
    if (isSlotUnavailableRpcError(error)) throw new SlotUnavailableError()
    throw error
  }
  return data as Booking
}

/** Stores the Stripe Checkout session id on a freshly created hold. */
export async function attachStripeSession(id: string, sessionId: string): Promise<void> {
  const { error } = await db()
    .from('bookings')
    .update({ stripe_session_id: sessionId })
    .eq('id', id)
  if (error) throw error
}

/**
 * Persists what Stripe actually charged after a promotion code (amount + saving
 * in FILS, plus the code string) so the admin dashboard reflects the discount
 * instead of the list total_price. Best-effort: the payment has already settled
 * by the time this runs, so a failure here must never bubble up and fail the
 * webhook (which would make Stripe retry and re-send emails) — it logs and
 * resolves, leaving the columns NULL so the dashboard falls back to total_price.
 */
export async function attachPaymentDetails(
  id: string,
  details: { amountPaidFils: number | null; discountFils: number | null; promoCode: string | null },
): Promise<void> {
  try {
    const { error } = await db()
      .from('bookings')
      .update({
        amount_paid: details.amountPaidFils,
        discount_amount: details.discountFils,
        promo_code: details.promoCode,
      })
      .eq('id', id)
    if (error) throw error
  } catch (err) {
    console.error('[booking] failed to persist payment details (ignored)', { id }, err)
  }
}

/**
 * Cancels a still-pending hold (best-effort) when Stripe session creation fails
 * after insert — frees the slot immediately instead of waiting 30 minutes.
 * Uses the cancel_pending_booking RPC so the transition stays idempotent.
 */
export async function releaseHold(id: string): Promise<void> {
  await db().rpc('cancel_pending_booking', { p_id: id })
}

export async function getBookingById(id: string): Promise<Booking | null> {
  if (!isSupabaseConfigured()) return null
  const { data, error } = await db().from('bookings').select('*').eq('id', id).maybeSingle()
  if (error) throw error
  return (data as Booking) ?? null
}

/**
 * Idempotently marks a booking paid via the confirm_booking_paid RPC. Only a
 * live hold transitions (→ paid / paid_new, default inspector assigned); a
 * repeated webhook gets null back and the caller skips emails.
 */
export async function markBookingPaid(
  id: string,
  paymentIntentId: string | null,
): Promise<Booking | null> {
  const { data, error } = await db().rpc('confirm_booking_paid', {
    p_id: id,
    p_payment_intent: paymentIntentId,
  })
  if (error) throw error
  return normaliseRpcRow(data)
}

/** Idempotently cancels a pending hold (Stripe expiry / payment failure) via
 *  the cancel_pending_booking RPC. Returns null when already processed. */
export async function markBookingCancelled(id: string): Promise<Booking | null> {
  const { data, error } = await db().rpc('cancel_pending_booking', { p_id: id })
  if (error) throw error
  return normaliseRpcRow(data)
}

/** RPCs that `returns public.bookings` yield a row object, or a row of nulls /
 *  null when the function returned NULL — normalise both to null. */
function normaliseRpcRow(data: unknown): Booking | null {
  if (!data) return null
  const row = data as Booking
  return row.id ? row : null
}

/** Stores the tentative Google Calendar event id after a paid booking. */
export async function attachCalendarEvent(id: string, eventId: string): Promise<void> {
  const { error } = await db()
    .from('bookings')
    .update({ google_calendar_event_id: eventId })
    .eq('id', id)
  if (error) throw error
}

/** Maps a snake_case DB row to the camelCase BookingRecord used by emails etc. */
export function rowToRecord(row: Booking): BookingRecord {
  return {
    id: row.id,
    status: row.booking_status,
    paymentStatus: row.payment_status,
    packageId: row.package_id,
    packageName: row.package_name,
    packagePrice: row.package_price,
    travelFee: row.travel_fee,
    totalPrice: row.total_price,
    amountPaid: row.amount_paid,
    discountAmount: row.discount_amount,
    promoCode: row.promo_code,
    customerName: row.customer_name,
    customerPhone: row.customer_phone,
    customerEmail: row.customer_email,
    carMake: row.car_make,
    carModel: row.car_model,
    carYear: row.car_year,
    vin: row.vin,
    plateNumber: row.plate_number,
    emirate: row.emirate as BookingRecord['emirate'],
    distanceClass: row.distance_class,
    parkingType: row.parking_type,
    address: row.address,
    locationLat: row.location_lat,
    locationLng: row.location_lng,
    inspectionDate: row.inspection_date,
    slotTime: row.slot_time,
    additionalNotes: row.additional_notes,
    stripeSessionId: row.stripe_session_id,
    stripePaymentIntentId: row.stripe_payment_intent_id,
    holdExpiresAt: row.hold_expires_at,
    paidAt: row.paid_at,
    cancelledAt: row.cancelled_at,
    assignedInspector: row.assigned_inspector,
    reportId: row.report_id,
    adminNotes: row.admin_notes,
    manualBooking: row.manual_booking,
    createdBy: row.created_by,
    googleCalendarEventId: row.google_calendar_event_id,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  }
}
